version: "2"

services:
  app:
    image: golang:1.8
    volumes:
      - .:/go/src/github.com/mistikel/go-cached
    working_dir: /go/src/github.com/mistikel/go-cached
    ports: 
      - "8000:8000"
    command: bash -c "go build && ./go-cached"
    links: 
      - redis

  redis:
    image: redis   
    ports: 
      - "6379:6379"